# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Deep Learning Para Aplicações de IA com PyTorch e Lightning</font>

## <font color='blue'>Lab 1</font>
## <font color='blue'>Anatomia de Uma Rede Neural Artificial com PyTorch e Lightning</font>

![title](imagens/Lab1.png)

## Instalando e Carregando os Pacotes

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
!pip install -q -U watermark

In [3]:
!pip install -q torch==1.13.0

In [4]:
!pip install -q pytorch-lightning==1.8.3

In [5]:
# Imports
import gc
import types
import pkg_resources
import torch
import pytorch_lightning as pl
from torch import nn, optim
from torch.autograd import Variable
from torch.utils.data import DataLoader
from pytorch_lightning.callbacks import ModelCheckpoint
#from pytorch_lightning.utilities.types import TRAIN_DATALOADERS
import warnings
warnings.filterwarnings("ignore")

In [6]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

pytorch_lightning: 1.8.3
torch            : 1.13.0



## Verificando o Ambiente de Desenvolvimento

In [7]:
# Verificando o dispositivo
processing_device = "cuda" if torch.cuda.is_available() else "cpu"

In [8]:
print(processing_device)

cpu


In [9]:
# Verificando se GPU pode ser usada (isso depende da plataforma CUDA estar instalada)
torch_aval = torch.cuda.is_available()

In [10]:
print(torch_aval)

False


In [11]:
# Labels para o relatório de verificação
lable_1 = 'Visão Geral do Ambiente'
lable_2 = 'Se NVIDIA-SMI não for encontrado, então CUDA não está disponível'
lable_3 = 'Fim da Checagem'

In [12]:
# Função para verificar o que está importado nesta sessão
def get_imports():

    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            name = val.__name__.split(".")[0]

        elif isinstance(val, type):            
            name = val.__module__.split(".")[0]

        poorly_named_packages = {"PIL": "Pillow", "sklearn": "scikit-learn"}

        if name in poorly_named_packages.keys():
            name = poorly_named_packages[name]

        yield name

In [13]:
# Imports nesta sessão
imports = list(set(get_imports()))

In [14]:
print(imports)

['__name__', 'python_version', '_i4', 'torch_aval', 'torch', '__package__', 'pkg_resources', '__', '_i6', '_', 'lable_3', '_i7', 'types', 'lable_2', '__spec__', '_i1', '_exit_code', 'warnings', '_i8', '_i10', '__doc__', 'lable_1', '_i3', 'get_ipython', '_i13', '_iii', 'Out', '___', '_i', 'exit', 'gc', 'In', '_i9', 'processing_device', '_i12', '_dh', 'get_imports', '_i5', '_i2', 'builtins', '_ih', '_i11', 'quit', '_ii', '__loader__', '_oh', 'pytorch_lightning']


In [15]:
# Loop para verificar os requerimentos
requirements = []
for m in pkg_resources.working_set:
    if m.project_name in imports and m.project_name!="pip":
        requirements.append((m.project_name, m.version))

In [16]:
print(requirements)

[('torch', '1.13.0')]


In [17]:
# Pasta com os dados (quando necessário)
pasta_dados = r'dados'

In [18]:
print(f'{lable_1:-^100}')
print()
print(f"Pasta de Dados: ", pasta_dados)
print(f"Versões dos Pacotes Requeridos: ", requirements)
print(f"Dispositivo Que Será Usado Para Treinar o Modelo: ", processing_device)
print(f"CUDA Está Disponível? ", torch_aval)
print("Versão do PyTorch: ", torch.__version__)
print("Versão do Lightning: ", pl.__version__)
print()
print(f'{lable_2:-^100}')
!nvidia-smi
gc.collect()
print()
print(f"Limpando a Memória da GPU (se disponível): ", torch.cuda.empty_cache())
print(f'{lable_3:-^100}')

--------------------------------------Visão Geral do Ambiente---------------------------------------

Pasta de Dados:  dados
Versões dos Pacotes Requeridos:  [('torch', '1.13.0')]
Dispositivo Que Será Usado Para Treinar o Modelo:  cpu
CUDA Está Disponível?  False
Versão do PyTorch:  1.13.0
Versão do Lightning:  1.8.3

------------------Se NVIDIA-SMI não for encontrado, então CUDA não está disponível------------------
/bin/bash: nvidia-smi: command not found

Limpando a Memória da GPU (se disponível):  None
------------------------------------------Fim da Checagem-------------------------------------------


> Se CUDA estiver instalado, a saída do comando nvidia-smi seria parecida com esta:

![title](imagens/nvidia-smi.png)

> Abaixo o relatório completo em uma única célula:

In [19]:
# Relatório completo

# Verificando o dispositivo
processing_device = "cuda" if torch.cuda.is_available() else "cpu"

# Verificando se GPU pode ser usada (isso depende da plataforma CUDA estar instalada)
torch_aval = torch.cuda.is_available()

# Labels para o relatório de verificação
lable_1 = 'Visão Geral do Ambiente'
lable_2 = 'Se NVIDIA-SMI não for encontrado, então CUDA não está disponível'
lable_3 = 'Fim da Checagem'

# Função para verificar o que está importado nesta sessão
def get_imports():

    for name, val in globals().items():
        if isinstance(val, types.ModuleType):
            name = val.__name__.split(".")[0]

        elif isinstance(val, type):            
            name = val.__module__.split(".")[0]

        poorly_named_packages = {"PIL": "Pillow", "sklearn": "scikit-learn"}

        if name in poorly_named_packages.keys():
            name = poorly_named_packages[name]

        yield name

# Imports nesta sessão
imports = list(set(get_imports()))

# Loop para verificar os requerimentos
requirements = []
for m in pkg_resources.working_set:
    if m.project_name in imports and m.project_name!="pip":
        requirements.append((m.project_name, m.version))
        
# Pasta com os dados (quando necessário)
pasta_dados = r'dados'

print(f'{lable_1:-^100}')
print()
print(f"Pasta de Dados: ", pasta_dados)
print(f"Versões dos Pacotes Requeridos: ", requirements)
print(f"Dispositivo Que Será Usado Para Treinar o Modelo: ", processing_device)
print(f"CUDA Está Disponível? ", torch_aval)
print("Versão do PyTorch: ", torch.__version__)
print("Versão do Lightning: ", pl.__version__)
print()
print(f'{lable_2:-^100}\n')
!nvidia-smi
gc.collect()
print()
print(f"Limpando a Memória da GPU (se disponível): ", torch.cuda.empty_cache())
print(f'\n{lable_3:-^100}')

--------------------------------------Visão Geral do Ambiente---------------------------------------

Pasta de Dados:  dados
Versões dos Pacotes Requeridos:  [('torch', '1.13.0')]
Dispositivo Que Será Usado Para Treinar o Modelo:  cpu
CUDA Está Disponível?  False
Versão do PyTorch:  1.13.0
Versão do Lightning:  1.8.3

------------------Se NVIDIA-SMI não for encontrado, então CUDA não está disponível------------------

/bin/bash: nvidia-smi: command not found

Limpando a Memória da GPU (se disponível):  None

------------------------------------------Fim da Checagem-------------------------------------------


## Datasets e DataLoaders

In [20]:
# Dados de entrada
dados_entrada = [Variable(torch.Tensor([0, 0])), 
                 Variable(torch.Tensor([0, 1])),
                 Variable(torch.Tensor([1, 0])),
                 Variable(torch.Tensor([1, 1]))]

In [21]:
# Dados de saída
dados_saida = [Variable(torch.Tensor([0])),
               Variable(torch.Tensor([1])),
               Variable(torch.Tensor([1])),
               Variable(torch.Tensor([0]))]

In [22]:
type(dados_entrada)

list

In [23]:
type(dados_saida)

list

In [24]:
# Dataset final
dados_final = list(zip(dados_entrada, dados_saida))

In [25]:
type(dados_final)

list

In [26]:
dados_final

[(tensor([0., 0.]), tensor([0.])),
 (tensor([0., 1.]), tensor([1.])),
 (tensor([1., 0.]), tensor([1.])),
 (tensor([1., 1.]), tensor([0.]))]

In [27]:
# Prepara o data loader
loader_treinamento = DataLoader(dados_final, batch_size = 1)

In [28]:
type(loader_treinamento)

torch.utils.data.dataloader.DataLoader

## Simple Net - Construindo o Primeiro Modelo com PyTorch e Lightning

https://pytorch.org/docs/stable/generated/torch.nn.Linear.html

https://pytorch.org/docs/stable/generated/torch.nn.Sigmoid.html

https://pytorch.org/docs/stable/generated/torch.nn.MSELoss.html

https://pytorch.org/docs/stable/optim.html

https://pytorch.org/docs/stable/generated/torch.optim.Adam.html

https://www.deeplearningbook.com.br/algoritmo-backpropagation-parte-2-treinamento-de-redes-neurais/

In [29]:
class SimpleNet(pl.LightningModule):
  
    # Método construtor
    # Usado para inicializar os parâmetros do modelo
    def __init__(self):

        super(SimpleNet, self).__init__()  
        
        self.input_layer = nn.Linear(2, 4)
        self.output_layer = nn.Linear(4, 1)
        self.sigmoid = nn.Sigmoid()
        self.loss = nn.MSELoss()

    # Método da passada para frente (forward)
    def forward(self, input):
        x = self.input_layer(input)
        x = self.sigmoid(x)
        output = self.output_layer(x)
        return output

    # Método de otimização
    def configure_optimizers(self):
        params = self.parameters()
        optimizer = optim.Adam(params = params, lr = 0.01)
        return optimizer

    # Método das passadas de treinamento
    def training_step(self, batch, batch_idx):
        entrada, saida = batch
        outputs = self(entrada) 
        loss = self.loss(outputs, saida)
        return loss 

**Compreendendo as dimensões em nn.Linear(2, 4)**

Especificação da função: torch.nn.Linear(in_features, out_features, bias=True)

- in_features – Tamanho da matriz dos dados de entrada. Em nosso exemplo 2 x 4.

- out_features – Tamanho da matriz dos dados de saída. Em nosso exemplo valor 4 x 1.

- bias - Valor aditivo (padrão igual a True).

Para que a multiplicação de matrizes aconteça, usamos a primeira dimensão de input e a primeira dimensão de output. Em nosso exemplo 2 x 4.

Cada valor de entrada será multiplicado por um valor de peso e ao final o modelo aprende os valores ideais dos pesos que representa a relação entre dados de entrada e saída.

Observe que usamos batch_size igual a 1 e nesse caso cada registro é uma unidade, o que influencia na dimensão das matrizes de dados.

Para facilitar a visualização use o link abaixo:

https://matrix.reshish.com/multiplication.php

**Compreendendo as dimensões em nn.Linear(4, 1)**

Aqui a primeira dimensão (4) é a saída da camada anterior. A segunda dimensão (1) é o número de previsões para cada. amostra de entrada.

## Loop de Treinamento

In [30]:
# Cria o modelo
modelo = SimpleNet()

In [31]:
# Cria o callback de checkpoint
checkpoint_callback = ModelCheckpoint()

In [32]:
# Cria o trainer
trainer = pl.Trainer(devices = 1,
                     accelerator = 'cpu',
                     max_epochs = 100,
                     callbacks = [checkpoint_callback])

GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs


In [33]:
# Treinamento
trainer.fit(modelo, train_dataloaders = loader_treinamento)


  | Name         | Type    | Params
-----------------------------------------
0 | input_layer  | Linear  | 12    
1 | output_layer | Linear  | 5     
2 | sigmoid      | Sigmoid | 0     
3 | loss         | MSELoss | 0     
-----------------------------------------
17        Trainable params
0         Non-trainable params
17        Total params
0.000     Total estimated model params size (MB)


Training: 0it [00:00, ?it/s]

`Trainer.fit` stopped: `max_epochs=100` reached.


In [34]:
modelo.device

device(type='cpu')

In [35]:
modelo.eval()

SimpleNet(
  (input_layer): Linear(in_features=2, out_features=4, bias=True)
  (output_layer): Linear(in_features=4, out_features=1, bias=True)
  (sigmoid): Sigmoid()
  (loss): MSELoss()
)

In [36]:
modelo.state_dict()

OrderedDict([('input_layer.weight',
              tensor([[ 0.2870, -0.4453],
                      [ 0.0521,  0.2923],
                      [ 0.4010,  0.3269],
                      [ 0.4998, -0.1653]])),
             ('input_layer.bias', tensor([0.6118, 0.2886, 0.3494, 0.5135])),
             ('output_layer.weight',
              tensor([[ 0.2369,  0.6355,  0.1961, -0.0797]])),
             ('output_layer.bias', tensor([-0.1158]))])

In [37]:
ls lightning_logs/*/

lightning_logs/version_0/:
checkpoints/  hparams.yaml

lightning_logs/version_1/:
checkpoints/  hparams.yaml


## Avaliação do Modelo

In [38]:
# Extrai o melhor modelo do checkpoint
melhor_modelo = (checkpoint_callback.best_model_path)

In [39]:
print(melhor_modelo)

/Users/dmpm/Dropbox/DSA/DeepLearningPyTorch/Cap02/Lab1/lightning_logs/version_1/checkpoints/epoch=99-step=400.ckpt


In [40]:
# Carrega o modelo do último checkpoint
modelo_final = modelo.load_from_checkpoint(checkpoint_callback.best_model_path)

In [41]:
modelo_final.state_dict()

OrderedDict([('input_layer.weight',
              tensor([[ 0.2870, -0.4453],
                      [ 0.0521,  0.2923],
                      [ 0.4010,  0.3269],
                      [ 0.4998, -0.1653]])),
             ('input_layer.bias', tensor([0.6118, 0.2886, 0.3494, 0.5135])),
             ('output_layer.weight',
              tensor([[ 0.2369,  0.6355,  0.1961, -0.0797]])),
             ('output_layer.bias', tensor([-0.1158]))])

In [42]:
# Novo registro de entrada
novo_dado_entrada_A = Variable(torch.Tensor([1, 1]))

In [43]:
# Faz a previsão
pred_A = modelo_final(novo_dado_entrada_A)

In [44]:
print(pred_A)

tensor([0.5346], grad_fn=<AddBackward0>)


In [45]:
print('A previsão de classe de pred_A é: ', int(pred_A.round()))

A previsão de classe de pred_A é:  1


In [46]:
# Novos dados de entrada
novos_dados = [Variable(torch.Tensor([1, 1])), 
               Variable(torch.Tensor([0, 0])),
               Variable(torch.Tensor([1, 0])),
               Variable(torch.Tensor([0, 1]))]

In [47]:
# Loop de teste
for val in novos_dados:
    
    # Faz a previsão de cada registro
    previsao = modelo_final(val)
    
    # Imprime o resultado
    print([int(val [0]), int(val [1])], int(previsao.round()))

[1, 1] 1
[0, 0] 0
[1, 0] 0
[0, 1] 1


In [48]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

pytorch_lightning: 1.8.3
torch            : 1.13.0



# Fim